// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReversiMvcApp.DatabaseContexts;

namespace ReversiMvcApp.Migrations
{
    [DbContext(typeof(ReversiDbContext))]
    [Migration("20220318125920_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("ReversiMvcApp.Models.Player", b =>
                {
                    b.Property<string>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberTied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberWon")
                        .HasColumnType("INTEGER");

                    b.HasKey("Guid");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
