export const GAME_EVENTS = Object.freeze({
    GAME_INIT: 'GAME_INIT',
    GAME_FINISHED: 'GAME_FINISHED',
    PLAYER_JOINED: 'PLAYER_JOINED',
    PLAYER_LEFT: 'PLAYER_LEFT',
    FICHE_PLACED: 'FICHE_PLACED',
    INVALID_FICHE_PLACEMENT: 'INVALID_FICHE_PLACEMENT',
    INVALID_SKIP_REQUEST: 'INVALID_SKIP_REQUEST',
    PLAYER_ABANDONED_TURN: 'PLAYER_ABANDONED_TURN',
});
